site_name: Documentação do Pibic - Embrapa Meio Ambiente

theme:
   name: readthedocs
   locale: pt_BR

markdown_extensions:
   - pymdownx.emoji
   - pymdownx.mark
   - pymdownx.tilde
   - pymdownx.highlight

